language: cpp
sudo: required
os: linux
compiler: g++
dist: trusty

before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt551-trusty
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install qt55[QTPACKAGE]

script:
  - source /opt/qt55/bin/qt55-env.sh
  - /opt/qt55/bin/qmake BankServer.pro
  - make

deploy:
  provider: s3
  access_key_id: "AKIAJY2M6WP2IDPWZ7IA"
  secret_access_key: "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"
  bucket: "bank-server"
